#!/bin/sh

if [ "$#" -ne 1 ]; then
    cat <<EOF
usage: git goodtogo [branch_name]

Merges the named branch into dev
EOF
  
  exit 1
fi

case "$1" in
  -h|-?|--help)
    cat <<EOF
usage: git goodtogo [branch_name]

Merges the named branch into dev
EOF
    exit
    ;;
esac

./manage.py jenkins && git checkout dev && git pull && git merge $1 && ./manage.py jenkins && git push && git branch -d $1
if [ "$?" -ne 0 ]; then
	cat <<EOF
Something went wrong, you must check where you left
EOF
fi
